// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cveyxdpmptnmcldjikxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZXl4ZHBtcHRubWNsZGppa3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzE5ODcsImV4cCI6MjA3NDU0Nzk4N30.9nrDz0QK-PpKQKg0YqcuPPAfB4KVR7A1RYKxpnYZw88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});